version: "3.9"
services:
  db:
    image: postgres:14.0-alpine3.14
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
  web:
    build: .
    restart: always
    ports:
      - "8080:8080"
      - "25:2525"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OH_MY_SMTP_API_KEY=${OH_MY_SMTP_API_KEY}
volumes:
  db-data:
