version: "3.9"
services:
  db:
    image: postgres:14.0-alpine3.14
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "587:1587"
      - "25:1587"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OH_MY_SMTP_API_KEY=${OH_MY_SMTP_API_KEY}
      - APPSIGNAL_PUSH_API_KEY=${APPSIGNAL_PUSH_API_KEY}
    volumes:
      - "caddy_data:/var/caddy:ro"
  caddy:
    build: ./caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
volumes:
  db_data:
  caddy_data:
  caddy_config:
