[main]
; strict_rfc1869=false
; smtputf8=true

[headers]
; add_received=true
; clean_auth_results=true
; show_version=true
max_lines=1000
max_received=100

; Haraka 3.x requires these sections even when using the upstream defaults.
[max]
bytes=26214400
mime_parts=1000
line_length=512
data_line_length=992

[message]
helo=Haraka is at your service.
close=closing connection. Have a jolly good day.

[uuid]
banner_chars=6
deny_chars=0

[haproxy]
hosts[]=
