name: CI
on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    env:
      MIX_ENV: test
      LOOPS_API_KEY: secret
    services:
      postgres:
        image: index.docker.io/library/postgres@sha256:c4c7a1585974706b5f72b8ab595e47399b23b2e03d93bbf75c1b0904be1803dc # ratchet:postgres:13.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: shroud_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Elixir
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
        with:
          elixir-version: "1.19.5"
          otp-version: "28"
      - name: Restore dependencies cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.MIX_ENV }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.MIX_ENV }}-
            ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: mix deps.compile
      - name: Check formatting
        run: mix format --check-formatted
      - name: Run linter
        run: mix credo
      - name: Check warnings
        run: mix compile --warnings-as-errors
      - name: Setup database
        run: mix ecto.setup
      - name: Run tests
        run: mix coveralls.json
      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          files: ./cover/excoveralls.json
          token: ${{ secrets.CODECOV_TOKEN }}
