name: Commitlint
on:
  pull_request:

jobs:
  commitlint:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
        shell: bash
      - name: Lint PR title
        run: |
          printf '%s\n' "${{ github.event.pull_request.title }}" | npx commitlint --verbose
        shell: bash
