on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

name: deploy

permissions:
  packages: write
  contents: read
  # allow issuing OIDC tokens for this workflow run
  # (required for Depot)
  id-token: write

jobs:
  deploy:
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: blacksmith-4vcpu-ubuntu-2404
            docker_platform: linux/amd64
          - platform: arm64
            runner: blacksmith-4vcpu-ubuntu-2404-arm
            docker_platform: linux/arm64
    runs-on: ${{ matrix.runner }}
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Depot
        uses: useblacksmith/setup-docker-builder@v1
      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=main
            type=sha
      - name: Build container
        uses: useblacksmith/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ matrix.docker_platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
