on:
  push:
    branches:
      - main
    paths:
      - 'shroud.email/**'
      - '.github/workflows/release-please.yml'
      - 'release-please-config.json'
      - '.release-please-manifest.json'

name: release-please

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ secrets.PAT }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
