name: Sobelow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  security-scan:
    permissions:
      contents: read
      security-events: write
    runs-on: blacksmith-2vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - name: Set up Elixir
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # ratchet:erlef/setup-beam@v1.24.0
        with:
          elixir-version: "1.16.3"
          otp-version: "26"
      - name: Restore dependencies cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # ratchet:actions/cache@v5
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-dev-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-dev-
            ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run Sobelow
        run: mix sobelow --format sarif --out results.sarif
      - name: Upload report
        uses: github/codeql-action/upload-sarif@ce64ddcb0d8d890d2df4a9d1c04ff297367dea2a # ratchet:github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
